<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationInsightsResourceId>/subscriptions/88d04478-33a7-462e-b7d5-99a49af06e8f/resourceGroups/DefaultResourceGroup-EUS/providers/microsoft.insights/components/Lab1</ApplicationInsightsResourceId>
    <UserSecretsId>fa21ca69-bd29-4020-aca7-d24ac56cf856</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
  </ItemGroup>

</Project>
